- job:
    name: sepia-fog-images
    project-type: freestyle
    defaults: global
    concurrent: false
    display-name: 'Sepia FOG Image Creator'
    node: teuthology
    quiet-period: 0
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 15
          num-to-keep: 30
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: DISTROS
          default: "ubuntu_14.04 ubuntu_16.04 centos_7.5 rhel_7.5"
          description: "Distro to capture images for: (e.g., 'ubuntu_16.04', 'centos_7.5' or 'ubuntu_16.04 rhel_7.5' for multiple distros)"
      - string:
          name: MACHINETYPES
          default: "smithi mira"
          description: "Machine types to capture images for.  (e.g., 'smithi' or 'smithi mira' for multiple machine types)"

    builders:
      - shell:
          !include-raw:
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw:
                      - ../../build/failure

    wrappers:
      - mask-passwords:
      - inject-passwords:
          global: true
          mask-password-params: true
